### ISSUE TITLE
Timing out with an error

### ISSUE THREAD

**Issue by kevindewalt** [prolego-team/neo-sophia#74]
<img width="2334" alt="Screen Shot 2023-08-03 at 1 47 47 PM" src="https://github.com/prolego-team/neo-sophia/assets/52680/fc1bb209-5ece-411a-9638-ce7770b2b364">

----

Who has most recently opened a checking account?

User:
Question: Who has most recently opened a checking account?

<name=None, function_call=None>

Assistant:
Thought: To find out who has most recently opened a checking account, you would need to check the 'checking_account' table for the latest account_open_date.

Action: { "query": "SELECT account_number, MAX(account_open_date) as Latest_date FROM checking_account" } to functions.query_database

<name=None, function_call={'name': 'query_database', 'arguments': '{ "query": "SELECT account_number, MAX(account_open_date) as Latest_date FROM checking_account" }'}>

Function:
Observation: [(102179, '2023-07-17')]

<name=query_database, function_call=None>

Assistant:
Thought: Now I have the account number for the most recently opened checking account. I need to match this account number with the corresponding customer guid in the 'products' table.

Action: { "query": "SELECT guid FROM products WHERE account_number = '102179'" } to functions.query_database

<name=None, function_call={'name': 'query_database', 'arguments': '{ "query": "SELECT guid FROM products WHERE account_number = '102179'" }'}>

Function:
Observation: [(876,)]

<name=query_database, function_call=None>

````
calling llm
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/kevindewalt/Documents/GitHub/neo-sophia/examples/bank_agent.py", line 115, in agent_wrapper
    for message in agent(question):
  File "/Users/kevindewalt/Documents/GitHub/neo-sophia/src/neosophia/agents/react.py", line 90, in run_once
    response = model(messages, functions=function_descriptions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevindewalt/Documents/GitHub/neo-sophia/src/neosophia/llmtools/openaiapi.py", line 128, in chat_func
    response = oai.ChatCompletion.create(messages=input_messages, model=model, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/neosophia/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: Bad gateway. {"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}} 502 {'error': {'code': 502, 'message': 'Bad gateway.', 'param': None, 'type': 'cf_bad_gateway'}} {'Date': 'Thu, 03 Aug 2023 17:44:31 GMT', 'Content-Type': 'application/json', 'Content-Length': '84', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Server': 'cloudflare', 'CF-RAY': '7f1056f94c2f32db-JAX', 'alt-svc': 'h3=":443"; ma=86400'
````

**Comment by jmpounders** [comment]
This just looks like an OpenAI API error.  502 response code.  Can you try again?

**Comment by kevindewalt** [comment]
Works. Do we need error handling?
